# Generated by Django 5.0.6 on 2025-08-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='criado_em',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='nome',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='lead',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
