# Generated by Django 5.0.6 on 2025-08-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_rename_criado_em_lead_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'Novo'), ('contacted', 'Contatado'), ('qualified', 'Qualificado')], default='new', max_length=20),
        ),
    ]
