# Generated by Django 5.0.6 on 2025-08-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'Novo'), ('contacted', 'Contatado'), ('qualified', 'Qualificado')], default='Novo', max_length=20),
        ),
    ]
